# Generated by Django 4.2.30 on 2026-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_level', models.IntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(max_length=50)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exams_exam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('content_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exams_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('override_total_score', models.FloatField(blank=True, null=True)),
                ('report_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'submissions_submission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisionGradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_unattempted', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vision_grading_visiongradingresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisionGradingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_correct', models.BooleanField(default=True)),
                ('error_classification', models.CharField(default='none', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vision_grading_visiongradingstep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(unique=True)),
                ('analytics_json', models.JSONField()),
                ('model_name', models.CharField(max_length=100)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'dashboard_examanalyticscache',
                'managed': True,
            },
        ),
    ]
